url: "https://simplyyounurse.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Simply You" # the name of your site, e.g. ACME Corp.
plugins: ["jekyll-sitemap"] # Jekyll plugins to use
description: "Simply You - Nurse Aesthetics. Real Expertise. Real Beauty."
color-0: "#ffffff" # background color for the site (White)
color-1: "#f6f2ed" # primary color for the site (Pink)
color-2: "#535442" # secondary color for the site (Olive)
color-3: "#2b2b2b" # accent color for the site (Black)
